apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gausstalk-frontend
  annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - talk.gausslabs.ai
    secretName: aks-ingress-tls
  rules:
  - host: talk.gausslabs.ai
    http:
      paths:
      - path: /home(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: gausstalk-frontend
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gausstalk-frontend-static
  annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /static/$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - talk.gausslabs.ai
    secretName: aks-ingress-tls
  rules:
  - host: talk.gausslabs.ai
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: gausstalk-frontend
            port:
              number: 80
        path: /static(/|$)(.*)
